version: '3.0'

services:
  main:
    container_name: main
    image: dpage/pgadmin4
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
